### ISSUE TITLE
Problem using "s" argument to make a search

### ISSUE THREAD

**Issue by carazo** [ericandrewlewis/WP_Query_Multisite#6]
Good evening,

Firstly congratulations and thanks for this class. This is great for WordPress proffessionals like me.

I have had an issue trying to make a search in the Network. The query doesn't work and I have seen which was the SQL request created.

I have tried to execute it directly over the MySQL/MariaDB server and I get a syntax error in a "UNION" inside the query.

There were 23 blogs in the network. I have solved it partially with a wp_query standar inside a foreach, but the best option could be make it totally compatible with this argument, too.

**Comment by jmslbam** [comment]
This is fixed in master
